# Generated by Django 5.0.6 on 2024-06-15 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('businessId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=9)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('priceRange', models.CharField(choices=[('AFD', 'Affordable'), ('MRG', 'Mid-Range'), ('GRM', 'Gourmet'), ('REF', 'Refined'), ('LVH', 'Lavish')], default='MRG', max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
